name: Run Analysis on Master

on:
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ master ]

jobs:
  analyze:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run analysis
        run: make analyze 
